### ISSUE TITLE
Allow opt-in to recursive unpublish

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-versioned#23]
## Acceptance Criteria

 * Unpublish and delete only affect the record they're called on by default (regardless of ownership relations)
 * Developers can opt-in to recursive unpublish and delete through explicit declarations (not inferred from ownership)
 * Developers can opt in on a per-record, per-relationship level
 * The behaviour can be applied both to versioned and non-versioned records
 * The behaviour works with all types of relationships: has_one, has_many, many_many
 * The behaviour tracks deletes in ChangeSets
 * The behaviour is well documented and discoverable by developers

 ## Notes

 * Does not require separate behaviours for unpublish and delete
 * Should not change existing ownership API
 * Makes not assumptions about exclusivity of an ownership relation
 * Excludes any UI warnings around the impact of an unpublish/delete action
 * Assumes this does not require changes to the existing `ChangeSet` model tracking
 * This was raised by @pitchandtone in https://github.com/silverstripe/silverstripe-framework/issues/7032#issuecomment-313363718
 * The reverse of this has already been implemented (an unpublished object will also unpublish it's owners) - see https://github.com/silverstripe/silverstripe-versioned/issues/25

## Tasks

 - [x] Implement DataObject.cascade_deletes config
 - [x] Ensure ChangeSets adds deleted cascade_deletes (adding item to campaign and deleting it)
 - [x] Ensure "unpublish" respects cascade_deletes without changesets
 - [x] Update unit tests

## PRs

  - [ ] https://github.com/silverstripe/silverstripe-versioned/pull/33
  - [x] https://github.com/silverstripe/silverstripe-framework/pull/7257
  - [ ] https://github.com/silverstripe/silverstripe-cms/pull/1919

## Related

 * [GridField support for versioned records](https://github.com/silverstripe/silverstripe-framework/issues/7032)

**Comment by chillu** [comment]
Actually I'm not sure if this is a good idea: Even for a straightforward `has_one: File`, unpublishing the file might have all kinds of side effects on other views. The same file can be in `has_one`, `has_many` and `many_many` relationships on other records as well. Do we need a way to determine "exclusive" ownership relationships, and throw an error if you try to apply that to more than one of these to a given record type?

**Comment by pitchandtone** [comment]
If we were relying on has_one or has_many to implicitly control this, it would be dangerous, but if it's explicitly related to using the $owns static then developers are opting-in already.

$owns may need documentation around its power.

Alternatively, you could create multiple static owns_publishes, owns_unpublishes, but I suspect people will just use onAfters to write more complex custom code and avoid owns altogether.

**Comment by tractorcow** [comment]
So I did have a think about it, and there are two kinds of exclusive relationships:

 - Relationships that can ONLY be exclusive. I.e. has_many (since the has_one on the other side can only point to one object).
 - Relationships that MAY be currently exclusive. I.e. a many_many to an object which may currently not point to other belongs_many_many than this owner, but it just as easily could.

We probably need an unpublish control similar to below

```php
class MyObject extends DataObject {
	/**
	 * Determine when to unpublish this object:
	 *   - Versioned::EXCLUSIVE_OWNER - Unpublished when only the exclusive owner is unpublished via has_many to this object (default)
	 *   - Versioned::SINGLE_OWNER - Unpublished when the last owner is unpublished
	 *   - Versioned::EXPLICIT - Object must be explicitly unpublished
	 */
	private static $unpublished_by = Versioned::EXCLUSIVE_OWNER;
}
```

We could also use this to replace the unlinkDisownedObjects (doesn't unpublish has_many objects, but sets the has_one on the object to 0 when doing a partial publish).

```

**Comment by sminnee** [comment]
There's something pretty important there:

*Auto-unpublish cascade === Auto-delete cascade*

I think that focusing on unpublish in isolation is going to lead to an inconsistent model. "unpublish" really just mean "delete from live", after all.

Because of this I think that `unpublished_by` is the wrong name for the config here. We want something like 'cascade_deletes'.

**Comment by tractorcow** [comment]
Do you want it to apply to non-versioned objects? I had thought of moving ownership out of versioned, and making it something that all objects can use.

**Comment by sminnee** [comment]
> Do you want it to apply to non-versioned objects?

I don't see that we have a choice without creating a fundamentally inconsistent model.

**Comment by tractorcow** [comment]
It's starting to feel like what we really want to do isn't going to be a non-breaking API.

**Comment by tractorcow** [comment]
I don't see how something can cascade delete if it isn't owned.

**Comment by sminnee** [comment]
> I don't see how something can cascade delete if it isn't owned.

By writing code that does it. :-P

If i understand your comment correctly, you mean more "it would seem inconsistent to have an owns property in our schema and not use it to control the behaviour of cascade deletes".

To which I'd say, sure, but:

 * `$owns` is kind of misnamed anyway, it's non-exclusive status means something more like "contains".
 * I'm not sure it's worth breaking the API here.
 * Cascade deletes is a properly of database relationships and is pretty well understood in the DB community.

**Comment by tractorcow** [comment]
Ok, so, owns for publishing, cascade for deletes?

**Comment by sminnee** [comment]
> What I mean is, I don't know why an object should cascade delete but not cascade publish. I thought cascades would be a subset of owns.

I agree that it would be more logical, but it's not worth breaking the API for.

> But back to what you are suggesting, you mean owns for publishing, cascade for deletes, and these are independent?

Yes, as a way of introducing the required functionality without breaking APIs, I was suggesting that.

**Comment by tractorcow** [comment]
ok, I think that sounds like a safe direction; One that doesn't need to rely on versioned right? Could it be a CasecadeDeleteExtension? (so it's not baked into dataobject)

**Comment by tractorcow** [comment]
Yeah it could be a part of versioned, maybe, or just ORM?

**Comment by tractorcow** [comment]
Question for @chillu 

We have looked at two possible directions:
 - explicit recursive unpublish; This is a feature of versioned
 - explicit recursive delete; This is a feature of dataobject / ORM, and automatically provides unpublish as well.
 
 I don't see either feature being significantly more difficult than one another; Recursive delete may be more useful in more cases, but will have a more significant effect on framework. Given that it'll be opt-in, it shouldn't have any unexpected consequences.
 
My preference is recursive delete, and we have a `deletes` config in exactly the same format as ownership, which is a list of strings pointing to relations that trigger delete.

@chillu if you are happy with this direction, I'll write up the new A/C in the body of this issue and write up tasks. Otherwise discuss. :)

**Comment by sminnee** [comment]
>@chillu if you are happy with this direction, I'll write up the new A/C in the body of this issue and write up tasks. Otherwise discuss. :)

I think we should clearly separate "ACs" (which is what's already there) and "recommended implementation" (something new to write). I think that we risk losing context of _why_ when we replace ACs with specific technical implementations.

**Comment by chillu** [comment]
I've added new ACs reflecting the state of discussion. Hopefully I haven't put too much implementation detail in there. In broad strokes, I think it should be opt-in, there should no inferring of cascades based on relationship/ownership type, and that we don't need to introduce a concept of "exclusive ownership" to make this work. 

Original ACs for reference:

 * When a record owns other records, calling `Versioned->doUnpublish()` also unpublishes child records
 * Developers can choose to opt in on a per-record, per-relationship level
 * This behaviour is well documented and discoverable by developers

**Comment by tractorcow** [comment]
Ah, yes I think we need to think about how this will interact with changesets. We don't use changesets for un-publish though, so if we make "unpublish uses changesets" that will be a larger story.

Also since, we never used changesets to un-publish, I'm not sure the API will support it without a re-engineer.
